[template]
src   = "nginx-proxy.conf.tmpl"
dest  = "/etc/nginx/conf.d/proxy.conf"
owner = "nginx"
mode  = "0644"
keys  = [ "/" ]

check_cmd = "nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "nginx -s reload"
